### ISSUE TITLE
IPS vs MMGS settings do not work correctly.

### ISSUE THREAD

**Issue by JRDeAmicis** [jliliamen/power-sm#3]
Hello! I love the idea of your tool. I am having some issues making it work.

When using MMGS settings and the base part is IPS the script will put the incorrect numbers in the appropriate fields.

[Test 1 Log.txt](https://github.com/jliliamen/power-sm/files/195860/Test.1.Log.txt)
![test 1 results](https://cloud.githubusercontent.com/assets/18170573/14147823/da90617c-f651-11e5-9f59-b5577d013c57.JPG)
![test 1](https://cloud.githubusercontent.com/assets/18170573/14147824/da909f7a-f651-11e5-85da-b39d753f46b3.JPG)

When using the IPS settings for an IPS part the script will put numbers / 25.4.

To make the IPS settings work you need to take your desired numbers and multiply them by 25.4.

Thoughts?

**Comment by AmenJlili** [comment]
Thanks! I'll check that out and keep you noted on this bug. I have not tested the IPS.
The reason why some features are failing to update (build) successfully is because the new values break the features.

**Comment by AmenJlili** [comment]
The bug was resolved. SW uses meters for length
